// const { Timestamp } = require("mongodb")
const mongoose=require('mongoose')

const recipeSchema=new mongoose.Schema({
    uuid:{
        type:String,
        required:true,
        unique:true
    },
    username:{
        type:String,
        required:true,
        trim:true,
    },
    profilePic:{
        type:String,
        required:true
    },
    userUuid:{
        type:String,
        required:true,
    },
    url:{
        type:String,
        required:true
    },
    likes:{
        type:[String],
        required:true
    },
    comments:{
        type:[{
            uuid:{
                type:String,
                required:true,
            },
            username:{
                type:String,
                required:true,
            },
            comment:{
                type:String,
                required:true,
            },
        }],
        required:true
    },
    name:{
        type:String,
        required:true
    },
    ingredients:{
        type:[{
            url:{
                type:String,
                required:true
            },
            name:{
                type:String,
                required:true
            }
        }]
    },
    steps:{
        type:[{
            url:{
                type:String,
                required:true
            },
            name:{
                type:String,
                required:true
            }
        }]
    },
}, {timestamps: true});

const Recipe=mongoose.model('recipe',recipeSchema)
module.exports=Recipe